-- =============================================
--           A9
-- Author:   CAILYN COCHRAN
-- DUE DATE: 11-15-2017
-- =============================================
--PART 2 
--CREATE TRIGGER

CREATE TRIGGER A9 
   ON  LGLINE 
   AFTER INSERT,DELETE,UPDATE
AS 
BEGIN

	DECLARE @INV_NUM NUMERIC(17)
	DECLARE @INV_TOTAL NUMERIC(9)

	IF(EXISTS(SELECT * FROM INSERTED))
	BEGIN 
		--LOGIC TO HANDLE RECORDS IN INSERTED
		DECLARE  INSERTED_CURSOR CURSOR FOR
		SELECT   INV_NUM, SUM(LINE_QTY*LINE_PRICE) AS INV_TOTAL
		FROM     INSERTED
		GROUP BY INV_NUM

		OPEN     INSERTED_CURSOR
		FETCH    NEXT FROM INSERTED_CURSOR
				INTO @INV_NUM, @INV_TOTAL
		WHILE (@@FETCH_STATUS = 0)
		BEGIN 
		     UPDATE LGINVOICE
			 SET    INV_TOTAL = INV_TOTAL + @INV_TOTAL
			 WHERE  INV_NUM = @INV_NUM
			 FETCH  NEXT FROM INSERTED_CURSOR
			        INTO @INV_NUM, @INV_TOTAL

		END
		CLOSE INSERTED_CURSOR
		DEALLOCATE INSERTED_CURSOR
	END

	IF(EXISTS (SELECT * FROM DELETED))
	BEGIN
		--LOGIC TO HANDLE RECORDS IN DELETED
		DECLARE  DELETED_CURSOR CURSOR FOR
		SELECT   INV_NUM, SUM(LINE_QTY*LINE_PRICE) AS INV_TOTAL
		FROM     DELETED
		GROUP BY INV_NUM
		
		OPEN     DELETED_CURSOR
		FETCH    NEXT FROM DELETED_CURSOR
				 INTO @INV_NUM, @INV_TOTAL
		WHILE (@@FETCH_STATUS = 0)
		BEGIN	
			UPDATE LGINVOICE
			SET    INV_TOTAL = INV_TOTAL - @INV_TOTAL
			WHERE  INV_NUM = @INV_NUM
			FETCH  NEXT FROM DELETED_CURSOR
				   INTO @INV_NUM, @INV_TOTAL
		END			
		CLOSE      DELETED_CURSOR
		DEALLOCATE DELETED_CURSOR
	END
END


--PART 3
-- TEST CODE

--VIEW INVOICE TABLE
SELECT *
FROM   LGINVOICE

--VIEW LINE TABLE
SELECT * 
FROM LGLINE

-- CREATE A TEMPORARY TABLE
SELECT * INTO LINE_TEMP
FROM LGLINE
WHERE INV_NUM IN (105)

SELECT *
FROM LINE_TEMP

--DELETE 
DELETE FROM LGLINE
WHERE INV_NUM IN (105)

--INSERT
INSERT INTO LGLINE
SELECT *
FROM LINE_TEMP

--UPDATE
UPDATE LGLINE
SET LINE_QTY = LINE_QTY +2
WHERE INV_NUM IN (104)






