--A10BC
--CIS 310-01 
--DUE 12/6/2017
--Cailyn Cochran
--1. Star Schema ERD
	-- Assignment 10 part A
--2. Write SQL script to create tables in star schema
--ADD IDENTITY AFTER INT FOR THE DIMENSION

--CREATE PRODUCT DIMENSION
CREATE TABLE PRODUCTDIM
(ProductID INT IDENTITY NOT NULL,
 Prod_SKU VARCHAR(15),
 Prod_Descript VARCHAR(255),
 Prod_Type VARCHAR(255),    
 Brand_ID NUMERIC(4, 0),
 Brand_Name VARCHAR(100),
 Brand_Type	VARCHAR(20)
)

--CREATE CUSTOMER DIMENSION
CREATE TABLE CUSTOMERDIM
(CustomerID INT IDENTITY NOT NULL,
 Cust_Code NUMERIC(38, 0),
 Cust_Fname VARCHAR(20),
 Cust_Lname VARCHAR(20),
 Cust_City VARCHAR(50),
 Cust_State CHAR(2),
 Cust_Zip CHAR(5)
 )

 --CREATE EMPLOYEE DIMENSION
 CREATE TABLE EMPLOYEEDIM
 (EmployeeID INT IDENTITY NOT NULL,
  Emp_Num NUMERIC(6, 0),
  Emp_Fname VARCHAR(20),
  Emp_Lname VARCHAR(20),
  Emp_Title VARCHAR(45),
  Dept_Num NUMERIC(5, 0),
  Dept_Name VARCHAR(50)
 )

 --CREATE TIME DIMENSION
 CREATE TABLE TIMEDIM
 (TimeID INT IDENTITY NOT NULL,
  Inv_Date DATE,
  Year CHAR(4),
  Month CHAR(2), 
  Quarter TINYINT
 )


 -- ALTER DIMENSION TABLES TO ADD CONSTRAINTS
 ALTER TABLE PRODUCTDIM
	ADD CONSTRAINT PK_PRODUCTDIM PRIMARY KEY (ProductID)
	
 ALTER TABLE CUSTOMERDIM
	ADD CONSTRAINT PK_CUSTOMERDIM PRIMARY KEY (CustomerID)

 ALTER TABLE EMPLOYEEDIM
	ADD CONSTRAINT PK_EMPLOYEEDIM PRIMARY KEY (EmployeeID)

 ALTER TABLE TIMEDIM
	ADD CONSTRAINT PK_TIMEDIM PRIMARY KEY(TimeID)


 --CREATE FACT TABLE

 CREATE TABLE FACT
 (CustomerID INT NOT NULL,
  ProductID INT NOT NULL,
  TimeID INT NOT NULL,
  EmployeeID INT NOT NULL,
  Line_Qty NUMERIC(18, 0),
  Line_Price NUMERIC(8, 2)
 )

 

--ALTER FACT TABLES TO ADD CONSTRAINTS

 ALTER TABLE FACT
 ADD CONSTRAINT PK_FACT PRIMARY KEY (CustomerID,TimeID,ProductID,EmployeeID),
		CONSTRAINT FK_FACT_CUSTOMERDIM FOREIGN KEY (CustomerID) REFERENCES CUSTOMERDIM,
		CONSTRAINT FK_FACT_TIMEDIM FOREIGN KEY (TimeID) REFERENCES TIMEDIM,
		CONSTRAINT FK_FACT_PRODUCTDIM FOREIGN KEY (ProductID) REFERENCES PRODUCTDIM,
		CONSTRAINT FK_FACT_EMPLOYEEDIM FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEEDIM

 --CREATE STAGING TABLE
 CREATE TABLE STAGING
 (CustomerID INT,
  TimeID INT,
  ProductID INT,
  EmployeeID INT,
  Line_Qty NUMERIC(18, 0),
  Line_Price NUMERIC(8, 2),
  Cust_Code NUMERIC(38, 0),
  Prod_SKU VARCHAR(15),
  Inv_Date DATE,
  Emp_Num NUMERIC(6, 0)
 )

 







   --create dim table
	--create constraints
   -- create dim table

   
   -- 2.
	--drop constraints
    --truncate
		-- removes everything from table that could have been populated
		-- to test in order to repopulate
	--alter table to add constraints

	-- Why do we populate dimension tables before the fact table?
		-- CONTAINS THE PK VALLUES THAT WILL BE FK VALUES IN THE FACT TABLE
	
	--INSERT INTO PRODUCTDIM
	--SELECT <NECESSARY ATT>
	--FROM LGPRODUCT P INNER JOIN LEGBRAND B
		-- ON P.BRAND_ID = B.BRAND_ID

-- SELECT *
-- FROM LGINVOICE I INNER JOIN LGLINE L
--      ON I.INV_NUM = L.INV_NUM
-- WHERE I.CUST_CODE = 86

--STAGING TABLE MAPS PRODUCTION DATA TO THE DATAWAREHOUSE KEYS







