-- A10BC
-- CIS 310-01
-- DUE: Dec 6, 2017
-- Cailyn Cochran

--What are the top 5 products in terms of sales (total quantity * price)?
SELECT * FROM PRODUCTDIM

SELECT P.PRODUCTID, P.PROD_SKU, P.PROD_DESCRIPT, SUM(F.LINE_QTY*F.LINE_PRICE) AS TOTAL_PRODUCT_SALES
FROM   PRODUCTDIM P INNER JOIN FACT F
	   ON P.PRODUCTID = F.PRODUCTID
GROUP BY P.PRODUCTID, P.PROD_SKU, P.PROD_DESCRIPT
HAVING SUM(F.LINE_QTY*F.LINE_PRICE) IN (SELECT TOP 5 SUM(F.LINE_QTY*F.LINE_PRICE) AS TOTAL_PRODUCT_SALES
										FROM   PRODUCTDIM P INNER JOIN FACT F
									    ON P.PRODUCTID = F.PRODUCTID
										GROUP BY P.PRODUCTID, P.PROD_SKU, P.PROD_DESCRIPT
										)
ORDER BY TOTAL_PRODUCT_SALES DESC

-- List the names of employees who have sold the most products in terms of amount of sales (total of quantity * price).

SELECT E.EMP_FNAME, E.EMP_LNAME, SUM(F.LINE_QTY * F.LINE_PRICE) AS SALES
FROM   EMPLOYEEDIM E INNER JOIN FACT F
	   ON F.EMPLOYEEID = E.EMPLOYEEID
GROUP BY E.EMP_FNAME, E.EMP_LNAME
HAVING SUM(F.LINE_QTY * F.LINE_PRICE) IN
	   (SELECT TOP 3 SUM(F.LINE_QTY * F.LINE_PRICE)
		FROM EMPLOYEEDIM E INNER JOIN FACT F
	    ON F.EMPLOYEEID = E.EMPLOYEEID
		GROUP BY E.EMP_FNAME, E.EMP_LNAME
		ORDER BY SUM(F.LINE_QTY * F.LINE_PRICE) DESC
	   )
ORDER BY SUM(F.LINE_QTY * F.LINE_PRICE) DESC

--List the total amount of sales by customer city and brand name. 
SELECT   C.CUST_CITY, P.BRAND_NAME, SUM(F.LINE_QTY * F.LINE_PRICE) AS TOTAL_SALES
FROM     CUSTOMERDIM C INNER JOIN FACT F 
	     ON C.CUSTOMERID = F.CUSTOMERID 
	     INNER JOIN PRODUCTDIM P 
	     ON P.PRODUCTID = F.PRODUCTID
GROUP BY C.CUST_CITY, P.BRAND_NAME
ORDER BY TOTAL_SALES DESC

--List the customer names of customers and the top 5 products each of these customers have bought. 

SELECT C.CUST_FNAME, C.CUST_LNAME, P.PROD_SKU, SUM(F.LINE_QTY * F.LINE_PRICE) AS TOTAL_PRODUCT_SALES
FROM   CUSTOMERDIM C INNER JOIN FACT F 
	   ON C.CUSTOMERID = F.CUSTOMERID 
	   INNER JOIN PRODUCTDIM P 
	   ON P.PRODUCTID = F.PRODUCTID
GROUP BY C.CUST_FNAME, C.CUST_LNAME, P.PROD_SKU
HAVING   SUM(F.LINE_QTY * F.LINE_PRICE) IN (SELECT TOP 5 SUM(FF.LINE_QTY * FF.LINE_PRICE) AS TOTAL_PRODUCT_SALES
											FROM   CUSTOMERDIM CD INNER JOIN FACT FF 
											ON CD.CUSTOMERID = FF.CUSTOMERID 
											INNER JOIN PRODUCTDIM PD 
											ON PD.PRODUCTID = FF.PRODUCTID
											WHERE CD.CUST_FNAME = C.CUST_FNAME
											GROUP BY C.CUST_FNAME, C.CUST_LNAME,P.PROD_SKU
											ORDER BY CD.CUST_LNAME SUM(FF.LINE_QTY * FF.LINE_PRICE) 
											)
ORDER BY C.CUST_LNAME DESC